### PR TITLE
Create TweakScale.cfg

### PR DESCRIPTION
**Pull request by miki-g**
for tweakscale compatibility

### CODE REVIEW

**Comment by miki-g** [comment]
:(

somewhere in ionrcs is hidden bug
(or in tweakscale, but i never see this bug before ionrcs)
parts is scaled without scaling thrust :/

**Comment by miki-g** [comment]
tested, working, ready for merge

**Comment by pellinor0** [comment]
With a coming change in TweakScale the TWEAKSCALEEXPONENTS will no longer be needed:
https://github.com/miki-g/TweakScale/commit/4329244702b7fa60b06744a5830bbf137f26883c

Since the IONRCS modules derive from moduleRCS they should properly inherit the thrust scaling from the next TweakScale version on.

**Comment by JPLRepo** [comment]
Why?
IONRCS does not currently support TweakScale.

**Comment by pellinor0** [comment]
This is a pull request for TweakScale support. What I am saying is that only the first commit from @miki-g is needed.

**Comment by miki-g** [comment]
ready to merge (?)

**Pull request merged**
